import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";
import { CATEGORIAS } from "@/lib/types";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFKD")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function getCategoryFromSlug(slug: string): string | null {
  const match = CATEGORIAS.find((category) => slugify(category) === slug);
  return match ?? null;
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function formatDate(date: Date | string): string {
  const d = typeof date === "string" ? new Date(date) : date;
  return new Intl.DateTimeFormat("es-CO", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(d);
}

export function generateWhatsAppMessage(
  storeName: string,
  storePhone: string,
  items: { nombre: string; cantidad: number; precio: number }[],
  total: number
): string {
  const itemsList = items
    .map((i) => `- ${i.nombre} x${i.cantidad}: ${formatPrice(i.precio * i.cantidad)}`)
    .join("\n");
  const message = `Hola! Quiero hacer un pedido desde Marketplace Tolima\n\nTienda: ${storeName}\n\nProductos:\n${itemsList}\n\nTotal: ${formatPrice(total)}\n\nEsta disponible?`;
  return `https://wa.me/${storePhone.replace(/\D/g, "")}?text=${encodeURIComponent(message)}`;
}

export function getStatusColor(status: string): string {
  const colors: Record<string, string> = {
    pendiente: "bg-yellow-100 text-yellow-800",
    confirmado: "bg-blue-100 text-blue-800",
    entregado: "bg-green-100 text-green-800",
    cancelado: "bg-red-100 text-red-800",
  };
  return colors[status] || "bg-gray-100 text-gray-800";
}

export function getStatusLabel(status: string): string {
  const labels: Record<string, string> = {
    pendiente: "Pendiente",
    confirmado: "Confirmado",
    entregado: "Entregado",
    cancelado: "Cancelado",
  };
  return labels[status] || status;
}

// ─────────────────────────────────────────────────────────────
// GALERÍA POR TIENDA
// Imágenes de picsum.photos con seeds únicos por negocio
// ─────────────────────────────────────────────────────────────
export const STORE_GALLERIES: Record<string, string[]> = {
  "minimercado-1": [
    "https://picsum.photos/seed/mini-g1/800/600",
    "https://picsum.photos/seed/mini-g2/800/600",
    "https://picsum.photos/seed/mini-g3/800/600",
    "https://picsum.photos/seed/mini-g4/800/600",
  ],
  "panaderia-1": [
    "https://picsum.photos/seed/pan-g1/800/600",
    "https://picsum.photos/seed/pan-g2/800/600",
    "https://picsum.photos/seed/pan-g3/800/600",
    "https://picsum.photos/seed/pan-g4/800/600",
  ],
  "ropa-1": [
    "https://picsum.photos/seed/ropa-g1/800/600",
    "https://picsum.photos/seed/ropa-g2/800/600",
    "https://picsum.photos/seed/ropa-g3/800/600",
    "https://picsum.photos/seed/ropa-g4/800/600",
  ],
  "ferreteria-1": [
    "https://picsum.photos/seed/ferr-g1/800/600",
    "https://picsum.photos/seed/ferr-g2/800/600",
    "https://picsum.photos/seed/ferr-g3/800/600",
    "https://picsum.photos/seed/ferr-g4/800/600",
  ],
  "farmacia-1": [
    "https://picsum.photos/seed/farm-g1/800/600",
    "https://picsum.photos/seed/farm-g2/800/600",
    "https://picsum.photos/seed/farm-g3/800/600",
    "https://picsum.photos/seed/farm-g4/800/600",
  ],
  "papeleria-1": [
    "https://picsum.photos/seed/papel-g1/800/600",
    "https://picsum.photos/seed/papel-g2/800/600",
    "https://picsum.photos/seed/papel-g3/800/600",
    "https://picsum.photos/seed/papel-g4/800/600",
  ],
  "tecnologia-1": [
    "https://picsum.photos/seed/tech-g1/800/600",
    "https://picsum.photos/seed/tech-g2/800/600",
    "https://picsum.photos/seed/tech-g3/800/600",
    "https://picsum.photos/seed/tech-g4/800/600",
  ],
  "belleza-1": [
    "https://picsum.photos/seed/bell-g1/800/600",
    "https://picsum.photos/seed/bell-g2/800/600",
    "https://picsum.photos/seed/bell-g3/800/600",
    "https://picsum.photos/seed/bell-g4/800/600",
  ],
};

// ─────────────────────────────────────────────────────────────
// TIENDAS DEMO
// ─────────────────────────────────────────────────────────────
export const DEMO_STORES = [
  {
    id: "minimercado-1",
    ownerId: "owner-mini-1",
    nombre: "Minimercado La Esquina",
    categoria: "Tienda de barrio",
    direccion: "Cra 5 #12-34, Barrio El Centro",
    ciudad: "Ibagué",
    telefono: "3001234567",
    descripcion: "Tu tienda de barrio de confianza. Abarrotes, bebidas, snacks y productos de primera necesidad. Atendemos desde las 6am todos los días con los mejores precios del barrio.",
    logo: "/images/stores/minimercado-logo.jpg",
    banner: "https://picsum.photos/seed/mini1banner/1400/500",
    calificacion: 4.8,
    totalReviews: 312,
    activo: true,
    createdAt: new Date(),
    tags: ["abarrotes", "bebidas", "snacks", "aseo"],
    horario: "Lun-Dom 6:00am – 10:00pm",
  },
  {
    id: "panaderia-1",
    ownerId: "owner-pan-1",
    nombre: "Panadería La Espiga Dorada",
    categoria: "Panadería",
    direccion: "Cll 15 #8-20, Barrio Belén",
    ciudad: "Ibagué",
    telefono: "3109876543",
    descripcion: "Pan artesanal horneado cada mañana. Pasteles, tortas personalizadas, croissants y café de origen tolimense. Más de 20 años endulzando el barrio.",
    logo: "/images/stores/panaderia.jpg",
    banner: "https://picsum.photos/seed/pan1banner/1400/500",
    calificacion: 4.9,
    totalReviews: 489,
    activo: true,
    createdAt: new Date(),
    tags: ["pan", "pasteles", "tortas", "café"],
    horario: "Lun-Sáb 5:30am – 8:00pm · Dom 6:00am – 2:00pm",
  },
  {
    id: "ropa-1",
    ownerId: "owner-ropa-1",
    nombre: "Boutique Moda Tolima",
    categoria: "Ropa",
    direccion: "Centro Comercial Combeima Local 45",
    ciudad: "Ibagué",
    telefono: "3157654321",
    descripcion: "Ropa de moda para hombre, mujer y niños. Marcas nacionales e internacionales. Tallas completas y asesoría de imagen personalizada.",
    logo: "/images/stores/logoboutique.jpg",
    banner: "https://picsum.photos/seed/ropa1banner/1400/500",
    calificacion: 4.7,
    totalReviews: 267,
    activo: true,
    createdAt: new Date(),
    tags: ["ropa", "moda", "calzado", "accesorios"],
    horario: "Lun-Sáb 9:00am – 7:00pm · Dom 10:00am – 4:00pm",
  },
  {
    id: "ferreteria-1",
    ownerId: "owner-ferr-1",
    nombre: "Ferretería El Constructor",
    categoria: "Ferretería",
    direccion: "Av. Ambalá #22-15, Zona Industrial",
    ciudad: "Ibagué",
    telefono: "3204567890",
    descripcion: "Todo para construcción y reparaciones del hogar. Herramientas, materiales, pinturas y asesoría técnica gratuita. Precios de mayorista al detal.",
    logo: "/images/stores/ferreteria.jpg",
    banner: "https://picsum.photos/seed/ferr1banner/1400/500",
    calificacion: 4.6,
    totalReviews: 198,
    activo: true,
    createdAt: new Date(),
    tags: ["herramientas", "construcción", "pinturas", "plomería"],
    horario: "Lun-Sáb 7:00am – 6:00pm",
  },
  {
    id: "farmacia-1",
    ownerId: "owner-farm-1",
    nombre: "Farmacia Salud y Vida",
    categoria: "Salud",
    direccion: "Cra 3 #18-25, Barrio Jordán",
    ciudad: "Ibagué",
    telefono: "3112345678",
    descripcion: "Medicamentos, vitaminas, productos de cuidado personal y asesoría farmacéutica. Servicio a domicilio disponible. Regentada por químico farmacéutico.",
    logo: "/images/stores/farmacia.jpg",
    banner: "https://picsum.photos/seed/farm1banner/1400/500",
    calificacion: 4.9,
    totalReviews: 534,
    activo: true,
    createdAt: new Date(),
    tags: ["medicamentos", "vitaminas", "cuidado personal", "domicilio"],
    horario: "Lun-Dom 7:00am – 10:00pm",
  },
  {
    id: "papeleria-1",
    ownerId: "owner-papel-1",
    nombre: "Papelería El Estudiante",
    categoria: "Papelería",
    direccion: "Frente al Colegio San Simón",
    ciudad: "Ibagué",
    telefono: "3187654321",
    descripcion: "Útiles escolares, impresiones, fotocopias, papelería y artículos de oficina. Servicio de impresión rápida y encuadernación profesional.",
    logo: "/images/stores/papeleria.jpg",
    banner: "https://picsum.photos/seed/papel1banner/1400/500",
    calificacion: 4.7,
    totalReviews: 156,
    activo: true,
    createdAt: new Date(),
    tags: ["útiles", "impresiones", "fotocopias", "oficina"],
    horario: "Lun-Sáb 7:00am – 7:00pm",
  },
  {
    id: "tecnologia-1",
    ownerId: "owner-tech-1",
    nombre: "TecnoShop Ibagué",
    categoria: "Tecnología",
    direccion: "Cll 19 #8-15, Centro",
    ciudad: "Ibagué",
    telefono: "3223456789",
    descripcion: "Celulares, accesorios, computadores y servicio técnico especializado. Distribuidor autorizado de las principales marcas. Garantía en todos los productos.",
    logo: "/images/stores/tecnoshop.jpg",
    banner: "https://picsum.photos/seed/tech1banner/1400/500",
    calificacion: 4.8,
    totalReviews: 423,
    activo: true,
    createdAt: new Date(),
    tags: ["celulares", "computadores", "accesorios", "servicio técnico"],
    horario: "Lun-Sáb 8:00am – 7:00pm",
  },
  {
    id: "belleza-1",
    ownerId: "owner-bell-1",
    nombre: "Salón de Belleza Glamour",
    categoria: "Belleza",
    direccion: "Cra 6 #10-20, Barrio Chapetón",
    ciudad: "Espinal",
    telefono: "3234567890",
    descripcion: "Cortes, tintes, tratamientos capilares, manicure y pedicure. Productos profesionales de belleza disponibles para la venta. Agenda tu cita en línea.",
    logo: "/images/stores/belleza.jpg",
    banner: "https://picsum.photos/seed/bell1banner/1400/500",
    calificacion: 4.9,
    totalReviews: 378,
    activo: true,
    createdAt: new Date(),
    tags: ["cabello", "manicure", "maquillaje", "tratamientos"],
    horario: "Mar-Sáb 8:00am – 7:00pm · Dom 9:00am – 3:00pm",
  },
  {
    id: "mascotas-1",
    ownerId: "owner-masc-1",
    nombre: "Mundo Mascotas Tolima",
    categoria: "Mascotas",
    direccion: "Cra 8 #15-30, Barrio Belén",
    ciudad: "Ibagué",
    telefono: "3145678901",
    descripcion: "Todo para el bienestar de tu mascota. Alimentos premium, accesorios, juguetes y productos de higiene para perros, gatos y más. Asesoría personalizada.",
    logo: "https://picsum.photos/seed/masc1logo/300/300",
    banner: "https://picsum.photos/seed/masc1banner/1400/500",
    calificacion: 4.8,
    totalReviews: 245,
    activo: true,
    createdAt: new Date(),
    tags: ["perros", "gatos", "alimento", "accesorios"],
    horario: "Lun-Sáb 8:00am – 7:00pm · Dom 9:00am – 2:00pm",
  },
  {
    id: "mascotas-2",
    ownerId: "owner-masc-2",
    nombre: "PetShop AnimalCare",
    categoria: "Mascotas",
    direccion: "Cll 42 #5-18, Centro Comercial La Estación",
    ciudad: "Ibagué",
    telefono: "3167890123",
    descripcion: "Tienda especializada en mascotas exóticas y convencionales. Acuarios, aves, reptiles, roedores. Alimentos especializados y accesorios importados.",
    logo: "https://picsum.photos/seed/masc2logo/300/300",
    banner: "https://picsum.photos/seed/masc2banner/1400/500",
    calificacion: 4.7,
    totalReviews: 189,
    activo: true,
    createdAt: new Date(),
    tags: ["acuarios", "aves", "reptiles", "alimento especial"],
    horario: "Lun-Dom 9:00am – 8:00pm",
  },
  {
    id: "mascotas-3",
    ownerId: "owner-masc-3",
    nombre: "Veterinaria Huellitas",
    categoria: "Mascotas",
    direccion: "Av. Ambala #30-12, Barrio El Salado",
    ciudad: "Ibagué",
    telefono: "3189012345",
    descripcion: "Clínica veterinaria con servicio de consulta, vacunación, cirugía y peluquería canina. Venta de medicamentos veterinarios y alimentos terapéuticos.",
    logo: "https://picsum.photos/seed/masc3logo/300/300",
    banner: "https://picsum.photos/seed/masc3banner/1400/500",
    calificacion: 4.9,
    totalReviews: 412,
    activo: true,
    createdAt: new Date(),
    tags: ["veterinaria", "vacunas", "peluqueria", "medicamentos"],
    horario: "Lun-Vie 7:00am – 6:00pm · Sáb 8:00am – 2:00pm",
  },
  // ── MELGAR Y ESPINAL ──────────────────────────────────────
  { id:"tec-mel-1", ownerId:"o-tm1", nombre:"DigiStore Melgar", categoria:"Tecnología", direccion:"Cra 5 #8-22, Centro", ciudad:"Melgar", telefono:"3201112233", descripcion:"Celulares, accesorios y servicio técnico en el corazón de Melgar.", logo:"https://picsum.photos/seed/tmel1logo/300/300", banner:"https://picsum.photos/seed/tmel1ban/1400/500", calificacion:4.6, totalReviews:134, activo:true, createdAt:new Date(), tags:["celulares","accesorios"], horario:"Lun-Sáb 9am-7pm" },
  { id:"tec-esp-1", ownerId:"o-te1", nombre:"TechPoint Espinal", categoria:"Tecnología", direccion:"Cll 10 #6-15, Barrio Centro", ciudad:"Espinal", telefono:"3212223344", descripcion:"Computadores, impresoras y accesorios tecnológicos para el hogar y la oficina.", logo:"https://picsum.photos/seed/tesp1logo/300/300", banner:"https://picsum.photos/seed/tesp1ban/1400/500", calificacion:4.5, totalReviews:98, activo:true, createdAt:new Date(), tags:["computadores","impresoras"], horario:"Lun-Sáb 8am-6pm" },
  { id:"tec-mel-2", ownerId:"o-tm2", nombre:"Electro Melgar", categoria:"Tecnología", direccion:"Av. Principal #12-40", ciudad:"Melgar", telefono:"3223334455", descripcion:"Electrodomésticos, televisores y equipos de sonido a los mejores precios.", logo:"https://picsum.photos/seed/tmel2logo/300/300", banner:"https://picsum.photos/seed/tmel2ban/1400/500", calificacion:4.4, totalReviews:76, activo:true, createdAt:new Date(), tags:["electrodomesticos","tv"], horario:"Lun-Dom 9am-8pm" },
  { id:"mod-mel-1", ownerId:"o-mm1", nombre:"Moda Tropical Melgar", categoria:"Ropa", direccion:"Cra 6 #5-30, Centro Comercial", ciudad:"Melgar", telefono:"3234445566", descripcion:"Ropa fresca y moderna ideal para el clima cálido de Melgar. Moda playera y casual.", logo:"https://picsum.photos/seed/mmel1logo/300/300", banner:"https://picsum.photos/seed/mmel1ban/1400/500", calificacion:4.7, totalReviews:201, activo:true, createdAt:new Date(), tags:["ropa","playera","casual"], horario:"Lun-Dom 9am-8pm" },
  { id:"mod-esp-1", ownerId:"o-me1", nombre:"Boutique Espinal Chic", categoria:"Ropa", direccion:"Cll 8 #4-18, Barrio El Progreso", ciudad:"Espinal", telefono:"3245556677", descripcion:"Moda femenina y masculina con las últimas tendencias. Tallas completas.", logo:"https://picsum.photos/seed/mesp1logo/300/300", banner:"https://picsum.photos/seed/mesp1ban/1400/500", calificacion:4.6, totalReviews:167, activo:true, createdAt:new Date(), tags:["moda","femenina","masculina"], horario:"Lun-Sáb 9am-7pm" },
  { id:"mod-mel-2", ownerId:"o-mm2", nombre:"Calzado y Moda Melgar", categoria:"Ropa", direccion:"Cra 7 #9-12, Zona Turística", ciudad:"Melgar", telefono:"3256667788", descripcion:"Calzado deportivo, casual y formal. Bolsos y accesorios de moda.", logo:"https://picsum.photos/seed/mmel2logo/300/300", banner:"https://picsum.photos/seed/mmel2ban/1400/500", calificacion:4.5, totalReviews:143, activo:true, createdAt:new Date(), tags:["calzado","bolsos"], horario:"Lun-Dom 8am-9pm" },
  { id:"bel-mel-1", ownerId:"o-bm1", nombre:"Spa & Belleza Melgar", categoria:"Belleza", direccion:"Cll 6 #3-25, Barrio Turístico", ciudad:"Melgar", telefono:"3267778899", descripcion:"Spa, masajes, tratamientos faciales y corporales. El mejor descanso en Melgar.", logo:"https://picsum.photos/seed/bmel1logo/300/300", banner:"https://picsum.photos/seed/bmel1ban/1400/500", calificacion:4.9, totalReviews:289, activo:true, createdAt:new Date(), tags:["spa","masajes","facial"], horario:"Mar-Dom 9am-7pm" },
  { id:"bel-esp-1", ownerId:"o-be1", nombre:"Estética Moderna Espinal", categoria:"Belleza", direccion:"Cra 9 #11-33, Centro", ciudad:"Espinal", telefono:"3278889900", descripcion:"Cortes, tintes, uñas y tratamientos capilares con productos profesionales.", logo:"https://picsum.photos/seed/besp1logo/300/300", banner:"https://picsum.photos/seed/besp1ban/1400/500", calificacion:4.7, totalReviews:198, activo:true, createdAt:new Date(), tags:["cortes","tintes","unas"], horario:"Lun-Sáb 8am-7pm" },
  { id:"bel-mel-2", ownerId:"o-bm2", nombre:"Nails & Beauty Melgar", categoria:"Belleza", direccion:"Av. Las Palmas #5-10", ciudad:"Melgar", telefono:"3289990011", descripcion:"Especialistas en uñas acrílicas, semipermanente y nail art. Cejas y pestañas.", logo:"https://picsum.photos/seed/bmel2logo/300/300", banner:"https://picsum.photos/seed/bmel2ban/1400/500", calificacion:4.8, totalReviews:312, activo:true, createdAt:new Date(), tags:["unas","nail art","pestanas"], horario:"Mar-Dom 9am-8pm" },
  { id:"sal-mel-1", ownerId:"o-sm1", nombre:"Droguería Melgar Salud", categoria:"Salud", direccion:"Cra 5 #7-14, Frente al Parque", ciudad:"Melgar", telefono:"3290001122", descripcion:"Medicamentos, vitaminas y productos de cuidado personal. Servicio a domicilio.", logo:"https://picsum.photos/seed/smel1logo/300/300", banner:"https://picsum.photos/seed/smel1ban/1400/500", calificacion:4.8, totalReviews:445, activo:true, createdAt:new Date(), tags:["medicamentos","domicilio"], horario:"Lun-Dom 7am-10pm" },
  { id:"sal-esp-1", ownerId:"o-se1", nombre:"Farmacia San Rafael Espinal", categoria:"Salud", direccion:"Cll 12 #8-20, Barrio San Rafael", ciudad:"Espinal", telefono:"3201112244", descripcion:"Farmacia con químico farmacéutico. Medicamentos genéricos y de marca.", logo:"https://picsum.photos/seed/sesp1logo/300/300", banner:"https://picsum.photos/seed/sesp1ban/1400/500", calificacion:4.7, totalReviews:321, activo:true, createdAt:new Date(), tags:["farmacia","genericos"], horario:"Lun-Dom 7am-9pm" },
  { id:"sal-mel-2", ownerId:"o-sm2", nombre:"Óptica Visión Melgar", categoria:"Salud", direccion:"Cra 6 #10-5, Centro", ciudad:"Melgar", telefono:"3212223355", descripcion:"Exámenes visuales, gafas formuladas, lentes de contacto y gafas de sol.", logo:"https://picsum.photos/seed/smel2logo/300/300", banner:"https://picsum.photos/seed/smel2ban/1400/500", calificacion:4.6, totalReviews:187, activo:true, createdAt:new Date(), tags:["optica","gafas","lentes"], horario:"Lun-Sáb 8am-6pm" },
  { id:"dep-mel-1", ownerId:"o-dm1", nombre:"Deportes Extremos Melgar", categoria:"Deportes", direccion:"Av. Rio Sumapaz #3-40", ciudad:"Melgar", telefono:"3223334466", descripcion:"Equipos para deportes acuáticos, ciclismo y aventura. Alquiler y venta.", logo:"https://picsum.photos/seed/dmel1logo/300/300", banner:"https://picsum.photos/seed/dmel1ban/1400/500", calificacion:4.8, totalReviews:267, activo:true, createdAt:new Date(), tags:["acuaticos","ciclismo","aventura"], horario:"Lun-Dom 8am-7pm" },
  { id:"dep-esp-1", ownerId:"o-de1", nombre:"SportZone Espinal", categoria:"Deportes", direccion:"Cll 15 #9-22, Barrio Deportivo", ciudad:"Espinal", telefono:"3234445577", descripcion:"Ropa deportiva, calzado y equipos para fútbol, natación y gimnasio.", logo:"https://picsum.photos/seed/desp1logo/300/300", banner:"https://picsum.photos/seed/desp1ban/1400/500", calificacion:4.6, totalReviews:198, activo:true, createdAt:new Date(), tags:["futbol","natacion","gimnasio"], horario:"Lun-Sáb 8am-7pm" },
  { id:"dep-mel-2", ownerId:"o-dm2", nombre:"Bicicletas y Más Melgar", categoria:"Deportes", direccion:"Cra 8 #6-18, Zona Rosa", ciudad:"Melgar", telefono:"3245556688", descripcion:"Bicicletas de montaña, ruta y urbanas. Repuestos y servicio técnico.", logo:"https://picsum.photos/seed/dmel2logo/300/300", banner:"https://picsum.photos/seed/dmel2ban/1400/500", calificacion:4.7, totalReviews:156, activo:true, createdAt:new Date(), tags:["bicicletas","repuestos"], horario:"Lun-Sáb 8am-6pm" },
  { id:"hog-mel-1", ownerId:"o-hm1", nombre:"Hogar & Deco Melgar", categoria:"Hogar", direccion:"Cll 7 #4-30, Centro", ciudad:"Melgar", telefono:"3256667799", descripcion:"Muebles, decoración y artículos para el hogar. Estilo moderno y tropical.", logo:"https://picsum.photos/seed/hmel1logo/300/300", banner:"https://picsum.photos/seed/hmel1ban/1400/500", calificacion:4.5, totalReviews:134, activo:true, createdAt:new Date(), tags:["muebles","decoracion"], horario:"Lun-Sáb 9am-6pm" },
  { id:"hog-esp-1", ownerId:"o-he1", nombre:"Ferrehogar Espinal", categoria:"Hogar", direccion:"Av. Principal #20-15", ciudad:"Espinal", telefono:"3267778800", descripcion:"Ferretería y artículos para el hogar. Pinturas, herramientas y plomería.", logo:"https://picsum.photos/seed/hesp1logo/300/300", banner:"https://picsum.photos/seed/hesp1ban/1400/500", calificacion:4.4, totalReviews:112, activo:true, createdAt:new Date(), tags:["ferreteria","pinturas","plomeria"], horario:"Lun-Sáb 7am-6pm" },
  { id:"hog-mel-2", ownerId:"o-hm2", nombre:"Colchones y Muebles Melgar", categoria:"Hogar", direccion:"Cra 9 #12-8, Zona Comercial", ciudad:"Melgar", telefono:"3278889911", descripcion:"Colchones ortopédicos, muebles de sala y comedor. Entrega a domicilio.", logo:"https://picsum.photos/seed/hmel2logo/300/300", banner:"https://picsum.photos/seed/hmel2ban/1400/500", calificacion:4.6, totalReviews:89, activo:true, createdAt:new Date(), tags:["colchones","muebles","sala"], horario:"Lun-Sáb 9am-7pm" },
  { id:"ser-mel-1", ownerId:"o-srm1", nombre:"Lavandería Express Melgar", categoria:"Servicios", direccion:"Cll 5 #3-12, Barrio El Centro", ciudad:"Melgar", telefono:"3289990022", descripcion:"Lavado y planchado de ropa en 24 horas. Servicio a domicilio disponible.", logo:"https://picsum.photos/seed/srmel1logo/300/300", banner:"https://picsum.photos/seed/srmel1ban/1400/500", calificacion:4.7, totalReviews:178, activo:true, createdAt:new Date(), tags:["lavanderia","planchado","domicilio"], horario:"Lun-Sáb 7am-7pm" },
  { id:"ser-esp-1", ownerId:"o-sre1", nombre:"Papelería y Servicios Espinal", categoria:"Servicios", direccion:"Cra 7 #9-40, Frente al Colegio", ciudad:"Espinal", telefono:"3290001133", descripcion:"Impresiones, fotocopias, encuadernación y útiles escolares.", logo:"https://picsum.photos/seed/sresp1logo/300/300", banner:"https://picsum.photos/seed/sresp1ban/1400/500", calificacion:4.5, totalReviews:234, activo:true, createdAt:new Date(), tags:["impresiones","fotocopias","utiles"], horario:"Lun-Sáb 7am-7pm" },
  { id:"ser-mel-2", ownerId:"o-srm2", nombre:"Foto Estudio Melgar", categoria:"Servicios", direccion:"Av. Turística #8-22", ciudad:"Melgar", telefono:"3201112255", descripcion:"Fotografía profesional, documentos, eventos y retratos. Impresión inmediata.", logo:"https://picsum.photos/seed/srmel2logo/300/300", banner:"https://picsum.photos/seed/srmel2ban/1400/500", calificacion:4.8, totalReviews:145, activo:true, createdAt:new Date(), tags:["fotografia","documentos","eventos"], horario:"Lun-Sáb 8am-6pm" },
  { id:"mas-mel-1", ownerId:"o-mam1", nombre:"PetLand Melgar", categoria:"Mascotas", direccion:"Cra 6 #7-18, Zona Turística", ciudad:"Melgar", telefono:"3212223366", descripcion:"Tienda de mascotas con alimentos, accesorios y servicio de grooming.", logo:"https://picsum.photos/seed/mammel1logo/300/300", banner:"https://picsum.photos/seed/mammel1ban/1400/500", calificacion:4.7, totalReviews:167, activo:true, createdAt:new Date(), tags:["mascotas","grooming","accesorios"], horario:"Lun-Dom 9am-7pm" },
  { id:"mas-esp-1", ownerId:"o-mae1", nombre:"Veterinaria El Espinal", categoria:"Mascotas", direccion:"Cll 10 #5-30, Barrio La Esperanza", ciudad:"Espinal", telefono:"3223334477", descripcion:"Consulta veterinaria, vacunación y venta de medicamentos para mascotas.", logo:"https://picsum.photos/seed/maesp1logo/300/300", banner:"https://picsum.photos/seed/maesp1ban/1400/500", calificacion:4.8, totalReviews:223, activo:true, createdAt:new Date(), tags:["veterinaria","vacunas","medicamentos"], horario:"Lun-Sáb 8am-6pm" },
  { id:"mas-mel-2", ownerId:"o-mam2", nombre:"Acuarios Melgar", categoria:"Mascotas", direccion:"Av. Principal #15-8", ciudad:"Melgar", telefono:"3234445588", descripcion:"Peces tropicales, acuarios, plantas acuáticas y todo para tu pecera.", logo:"https://picsum.photos/seed/mammel2logo/300/300", banner:"https://picsum.photos/seed/mammel2ban/1400/500", calificacion:4.6, totalReviews:98, activo:true, createdAt:new Date(), tags:["peces","acuarios","plantas"], horario:"Lun-Dom 9am-6pm" },
];

export const DEMO_PRODUCTS = [
  // PRODUCTOS MELGAR Y ESPINAL
  {id:"tmel1-p1",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Celular Samsung A15",precio:650000,descripcion:"Smartphone 128GB camara triple.",imagen:"https://picsum.photos/seed/techp1/400/400",stock:20,categoria:"Celulares",activo:true,createdAt:new Date()},
  {id:"tmel1-p2",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Funda Celular",precio:15000,descripcion:"Funda protectora silicona.",imagen:"https://picsum.photos/seed/techp2/400/400",stock:50,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tmel1-p3",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Audifonos Inalambricos",precio:75000,descripcion:"Audifonos bluetooth 5.0.",imagen:"https://picsum.photos/seed/techp3/400/400",stock:25,categoria:"Audio",activo:true,createdAt:new Date()},
  {id:"tmel1-p4",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Cargador Rapido 20W",precio:35000,descripcion:"Cargador USB-C 20W.",imagen:"https://picsum.photos/seed/techp4/400/400",stock:40,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tmel1-p5",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Vidrio Templado x2",precio:12000,descripcion:"Protector pantalla vidrio.",imagen:"https://picsum.photos/seed/techp5/400/400",stock:60,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tmel1-p6",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Cable USB-C 2m",precio:18000,descripcion:"Cable USB-C carga rapida 2 metros.",imagen:"https://picsum.photos/seed/techp16/400/400",stock:45,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tmel1-p7",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Soporte Celular Escritorio",precio:22000,descripcion:"Soporte ajustable para celular.",imagen:"https://picsum.photos/seed/techp17/400/400",stock:30,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tmel1-p8",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Memoria MicroSD 64GB",precio:45000,descripcion:"Memoria MicroSD 64GB Clase 10.",imagen:"https://picsum.photos/seed/techp18/400/400",stock:35,categoria:"Almacenamiento",activo:true,createdAt:new Date()},
  {id:"tmel1-p9",storeId:"tec-mel-1",storeName:"DigiStore Melgar",nombre:"Anillo Luz LED Selfie",precio:32000,descripcion:"Anillo luz LED para selfies y videos.",imagen:"https://picsum.photos/seed/techp19/400/400",stock:20,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tesp1-p1",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Laptop Lenovo 15",precio:1850000,descripcion:"Laptop Intel Core i5 8GB RAM.",imagen:"https://picsum.photos/seed/techp6/400/400",stock:5,categoria:"Computadores",activo:true,createdAt:new Date()},
  {id:"tesp1-p2",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Mouse Optico USB",precio:22000,descripcion:"Mouse optico 1200 DPI.",imagen:"https://picsum.photos/seed/techp7/400/400",stock:35,categoria:"Computadores",activo:true,createdAt:new Date()},
  {id:"tesp1-p3",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Teclado USB Español",precio:38000,descripcion:"Teclado USB layout español.",imagen:"https://picsum.photos/seed/techp8/400/400",stock:20,categoria:"Computadores",activo:true,createdAt:new Date()},
  {id:"tesp1-p4",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Impresora Epson L3250",precio:580000,descripcion:"Impresora multifuncional WiFi.",imagen:"https://picsum.photos/seed/techp9/400/400",stock:8,categoria:"Impresoras",activo:true,createdAt:new Date()},
  {id:"tesp1-p5",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Memoria RAM 8GB",precio:120000,descripcion:"Memoria DDR4 8GB 3200MHz.",imagen:"https://picsum.photos/seed/techp10/400/400",stock:15,categoria:"Computadores",activo:true,createdAt:new Date()},
  {id:"tesp1-p6",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Webcam Full HD 1080p",precio:95000,descripcion:"Camara web Full HD con microfono.",imagen:"https://picsum.photos/seed/techp20/400/400",stock:12,categoria:"Computadores",activo:true,createdAt:new Date()},
  {id:"tesp1-p7",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Hub USB 4 Puertos",precio:28000,descripcion:"Hub USB 3.0 con 4 puertos.",imagen:"https://picsum.photos/seed/techp21/400/400",stock:25,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tesp1-p8",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Pad Mouse Ergonomico",precio:15000,descripcion:"Pad mouse con soporte de muneca.",imagen:"https://picsum.photos/seed/techp22/400/400",stock:30,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tesp1-p9",storeId:"tec-esp-1",storeName:"TechPoint Espinal",nombre:"Cable HDMI 3m",precio:25000,descripcion:"Cable HDMI 2.0 alta velocidad 3m.",imagen:"https://picsum.photos/seed/techp23/400/400",stock:20,categoria:"Cables",activo:true,createdAt:new Date()},
  {id:"tmel2-p1",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"TV 43 pulgadas 4K",precio:980000,descripcion:"Smart TV 43 pulgadas 4K UHD.",imagen:"https://picsum.photos/seed/techp11/400/400",stock:6,categoria:"Television",activo:true,createdAt:new Date()},
  {id:"tmel2-p2",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Ventilador Torre",precio:145000,descripcion:"Ventilador torre 3 velocidades.",imagen:"https://picsum.photos/seed/techp12/400/400",stock:12,categoria:"Electrodomesticos",activo:true,createdAt:new Date()},
  {id:"tmel2-p3",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Licuadora 600W",precio:185000,descripcion:"Licuadora 600W 6 velocidades.",imagen:"https://picsum.photos/seed/techp13/400/400",stock:10,categoria:"Electrodomesticos",activo:true,createdAt:new Date()},
  {id:"tmel2-p4",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Plancha Ropa Vapor",precio:95000,descripcion:"Plancha a vapor 2200W.",imagen:"https://picsum.photos/seed/techp14/400/400",stock:15,categoria:"Electrodomesticos",activo:true,createdAt:new Date()},
  {id:"tmel2-p5",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Parlante Portatil 20W",precio:120000,descripcion:"Parlante bluetooth resistente agua.",imagen:"https://picsum.photos/seed/techp15/400/400",stock:18,categoria:"Audio",activo:true,createdAt:new Date()},
  {id:"tmel2-p6",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Cafetera Electrica 12 Tazas",precio:135000,descripcion:"Cafetera electrica programable 12 tazas.",imagen:"https://picsum.photos/seed/techp24/400/400",stock:8,categoria:"Electrodomesticos",activo:true,createdAt:new Date()},
  {id:"tmel2-p7",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Sandwichera Antiadherente",precio:75000,descripcion:"Sandwichera electrica antiadherente.",imagen:"https://picsum.photos/seed/techp25/400/400",stock:14,categoria:"Electrodomesticos",activo:true,createdAt:new Date()},
  {id:"tmel2-p8",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Batidora Manual 300W",precio:68000,descripcion:"Batidora manual 5 velocidades.",imagen:"https://picsum.photos/seed/techp26/400/400",stock:16,categoria:"Electrodomesticos",activo:true,createdAt:new Date()},
  {id:"tmel2-p9",storeId:"tec-mel-2",storeName:"Electro Melgar",nombre:"Extension Electrica 4 Tomas",precio:32000,descripcion:"Extension 4 tomas con proteccion.",imagen:"https://picsum.photos/seed/techp27/400/400",stock:22,categoria:"Electrico",activo:true,createdAt:new Date()},

  {id:"mmel1-p1",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Vestido Playero",precio:55000,descripcion:"Vestido fresco ideal para clima calido.",imagen:"https://picsum.photos/seed/modp1/400/400",stock:20,categoria:"Ropa Mujer",activo:true,createdAt:new Date()},
  {id:"mmel1-p2",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Short Deportivo",precio:38000,descripcion:"Short deportivo secado rapido.",imagen:"https://picsum.photos/seed/modp2/400/400",stock:30,categoria:"Ropa Hombre",activo:true,createdAt:new Date()},
  {id:"mmel1-p3",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Camiseta Estampada",precio:28000,descripcion:"Camiseta algodon estampado tropical.",imagen:"https://picsum.photos/seed/modp3/400/400",stock:40,categoria:"Ropa Hombre",activo:true,createdAt:new Date()},
  {id:"mmel1-p4",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Sandalias Playa",precio:45000,descripcion:"Sandalias comodas para playa.",imagen:"https://picsum.photos/seed/modp4/400/400",stock:25,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"mmel1-p5",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Gorra Sol",precio:22000,descripcion:"Gorra con proteccion UV.",imagen:"https://picsum.photos/seed/modp5/400/400",stock:35,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mmel1-p6",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Bikini Dos Piezas",precio:58000,descripcion:"Bikini dos piezas estampado tropical.",imagen:"https://picsum.photos/seed/modp16/400/400",stock:18,categoria:"Ropa Mujer",activo:true,createdAt:new Date()},
  {id:"mmel1-p7",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Pantaloneta Playa Hombre",precio:42000,descripcion:"Pantaloneta playa secado rapido.",imagen:"https://picsum.photos/seed/modp17/400/400",stock:28,categoria:"Ropa Hombre",activo:true,createdAt:new Date()},
  {id:"mmel1-p8",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Pareo Playa",precio:35000,descripcion:"Pareo multiuso para playa.",imagen:"https://picsum.photos/seed/modp18/400/400",stock:22,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mmel1-p9",storeId:"mod-mel-1",storeName:"Moda Tropical Melgar",nombre:"Lentes de Sol Deportivos",precio:48000,descripcion:"Lentes sol deportivos polarizados.",imagen:"https://picsum.photos/seed/modp19/400/400",stock:20,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mesp1-p1",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Blusa Elegante",precio:48000,descripcion:"Blusa gasa con detalles bordados.",imagen:"https://picsum.photos/seed/modp6/400/400",stock:18,categoria:"Ropa Mujer",activo:true,createdAt:new Date()},
  {id:"mesp1-p2",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Jean Skinny",precio:72000,descripcion:"Jean skinny tiro alto.",imagen:"https://picsum.photos/seed/modp7/400/400",stock:22,categoria:"Ropa Mujer",activo:true,createdAt:new Date()},
  {id:"mesp1-p3",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Camisa Formal",precio:65000,descripcion:"Camisa formal manga larga.",imagen:"https://picsum.photos/seed/modp8/400/400",stock:15,categoria:"Ropa Hombre",activo:true,createdAt:new Date()},
  {id:"mesp1-p4",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Bolso Tote",precio:85000,descripcion:"Bolso tote cuero sintetico.",imagen:"https://picsum.photos/seed/modp9/400/400",stock:10,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mesp1-p5",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Cinturon Cuero",precio:35000,descripcion:"Cinturon cuero genuino.",imagen:"https://picsum.photos/seed/modp10/400/400",stock:20,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mesp1-p6",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Vestido Coctel",precio:95000,descripcion:"Vestido coctel elegante tallas S-XL.",imagen:"https://picsum.photos/seed/modp20/400/400",stock:12,categoria:"Ropa Mujer",activo:true,createdAt:new Date()},
  {id:"mesp1-p7",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Pantalon Formal Hombre",precio:78000,descripcion:"Pantalon formal corte clasico.",imagen:"https://picsum.photos/seed/modp21/400/400",stock:16,categoria:"Ropa Hombre",activo:true,createdAt:new Date()},
  {id:"mesp1-p8",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Bufanda Elegante",precio:28000,descripcion:"Bufanda suave multicolor.",imagen:"https://picsum.photos/seed/modp22/400/400",stock:25,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mesp1-p9",storeId:"mod-esp-1",storeName:"Boutique Espinal Chic",nombre:"Cartera Mano",precio:68000,descripcion:"Cartera de mano elegante.",imagen:"https://picsum.photos/seed/modp23/400/400",stock:14,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mmel2-p1",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Tenis Running",precio:135000,descripcion:"Tenis running suela amortiguada.",imagen:"https://picsum.photos/seed/modp11/400/400",stock:15,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"mmel2-p2",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Zapato Formal",precio:120000,descripcion:"Zapato formal cuero sintetico.",imagen:"https://picsum.photos/seed/modp12/400/400",stock:12,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"mmel2-p3",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Bota Casual",precio:95000,descripcion:"Bota casual unisex.",imagen:"https://picsum.photos/seed/modp13/400/400",stock:10,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"mmel2-p4",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Bolso Bandolera",precio:65000,descripcion:"Bolso bandolera ajustable.",imagen:"https://picsum.photos/seed/modp14/400/400",stock:18,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mmel2-p5",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Gafas de Sol",precio:42000,descripcion:"Gafas sol proteccion UV400.",imagen:"https://picsum.photos/seed/modp15/400/400",stock:25,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mmel2-p6",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Sandalias Cuero Hombre",precio:85000,descripcion:"Sandalias cuero genuino hombre.",imagen:"https://picsum.photos/seed/modp24/400/400",stock:14,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"mmel2-p7",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Zapatillas Casa",precio:32000,descripcion:"Zapatillas comodas para casa.",imagen:"https://picsum.photos/seed/modp25/400/400",stock:20,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"mmel2-p8",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Mochila Urbana",precio:75000,descripcion:"Mochila urbana resistente agua.",imagen:"https://picsum.photos/seed/modp26/400/400",stock:16,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"mmel2-p9",storeId:"mod-mel-2",storeName:"Calzado y Moda Melgar",nombre:"Reloj Casual",precio:95000,descripcion:"Reloj casual correa cuero.",imagen:"https://picsum.photos/seed/modp27/400/400",stock:10,categoria:"Accesorios",activo:true,createdAt:new Date()},

  {id:"bmel1-p1",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Masaje Relajante 60min",precio:80000,descripcion:"Masaje corporal relajante 60 minutos.",imagen:"https://picsum.photos/seed/belp1/400/400",stock:10,categoria:"Servicios",activo:true,createdAt:new Date()},
  {id:"bmel1-p2",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Facial Hidratante",precio:65000,descripcion:"Tratamiento facial hidratante profundo.",imagen:"https://picsum.photos/seed/belp2/400/400",stock:8,categoria:"Servicios",activo:true,createdAt:new Date()},
  {id:"bmel1-p3",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Crema Corporal 300ml",precio:45000,descripcion:"Crema corporal hidratante premium.",imagen:"https://picsum.photos/seed/belp3/400/400",stock:20,categoria:"Cuidado Personal",activo:true,createdAt:new Date()},
  {id:"bmel1-p4",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Aceite Esencial Lavanda",precio:28000,descripcion:"Aceite esencial lavanda 30ml.",imagen:"https://picsum.photos/seed/belp4/400/400",stock:25,categoria:"Aromaterapia",activo:true,createdAt:new Date()},
  {id:"bmel1-p5",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Kit Spa en Casa",precio:95000,descripcion:"Kit completo spa en casa 5 productos.",imagen:"https://picsum.photos/seed/belp5/400/400",stock:12,categoria:"Kits",activo:true,createdAt:new Date()},
  {id:"bmel1-p6",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Exfoliante Corporal 200g",precio:38000,descripcion:"Exfoliante corporal natural cafe.",imagen:"https://picsum.photos/seed/belp16/400/400",stock:18,categoria:"Cuidado Personal",activo:true,createdAt:new Date()},
  {id:"bmel1-p7",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Masaje Piedras Calientes",precio:95000,descripcion:"Sesion masaje con piedras calientes.",imagen:"https://picsum.photos/seed/belp17/400/400",stock:6,categoria:"Servicios",activo:true,createdAt:new Date()},
  {id:"bmel1-p8",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Vela Aromatica Lavanda",precio:22000,descripcion:"Vela aromatica lavanda 150g.",imagen:"https://picsum.photos/seed/belp18/400/400",stock:30,categoria:"Aromaterapia",activo:true,createdAt:new Date()},
  {id:"bmel1-p9",storeId:"bel-mel-1",storeName:"Spa & Belleza Melgar",nombre:"Bata Spa Premium",precio:68000,descripcion:"Bata spa microfibra suave.",imagen:"https://picsum.photos/seed/belp19/400/400",stock:15,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"besp1-p1",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Tinte Cabello",precio:55000,descripcion:"Tinte profesional con tratamiento.",imagen:"https://picsum.photos/seed/belp6/400/400",stock:15,categoria:"Cabello",activo:true,createdAt:new Date()},
  {id:"besp1-p2",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Manicure Semipermanente",precio:35000,descripcion:"Manicure semipermanente larga duracion.",imagen:"https://picsum.photos/seed/belp7/400/400",stock:20,categoria:"Manicure",activo:true,createdAt:new Date()},
  {id:"besp1-p3",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Shampoo Profesional 500ml",precio:42000,descripcion:"Shampoo profesional keratina.",imagen:"https://picsum.photos/seed/belp8/400/400",stock:18,categoria:"Cabello",activo:true,createdAt:new Date()},
  {id:"besp1-p4",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Mascarilla Capilar 250g",precio:38000,descripcion:"Mascarilla reparadora cabello danado.",imagen:"https://picsum.photos/seed/belp9/400/400",stock:22,categoria:"Cabello",activo:true,createdAt:new Date()},
  {id:"besp1-p5",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Esmalte Gel x6",precio:32000,descripcion:"Set 6 esmaltes gel colores.",imagen:"https://picsum.photos/seed/belp10/400/400",stock:30,categoria:"Manicure",activo:true,createdAt:new Date()},
  {id:"besp1-p6",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Secador Cabello Profesional",precio:125000,descripcion:"Secador profesional 2000W ionico.",imagen:"https://picsum.photos/seed/belp20/400/400",stock:8,categoria:"Equipos",activo:true,createdAt:new Date()},
  {id:"besp1-p7",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Cepillo Alisador Electrico",precio:85000,descripcion:"Cepillo alisador ceramica.",imagen:"https://picsum.photos/seed/belp21/400/400",stock:10,categoria:"Equipos",activo:true,createdAt:new Date()},
  {id:"besp1-p8",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Aceite Argan 100ml",precio:45000,descripcion:"Aceite argan puro cabello.",imagen:"https://picsum.photos/seed/belp22/400/400",stock:20,categoria:"Cabello",activo:true,createdAt:new Date()},
  {id:"besp1-p9",storeId:"bel-esp-1",storeName:"Estetica Moderna Espinal",nombre:"Kit Manicure Profesional",precio:55000,descripcion:"Kit manicure 12 piezas profesional.",imagen:"https://picsum.photos/seed/belp23/400/400",stock:15,categoria:"Manicure",activo:true,createdAt:new Date()},
  {id:"bmel2-p1",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Unas Acrilicas",precio:65000,descripcion:"Unas acrilicas con diseno incluido.",imagen:"https://picsum.photos/seed/belp11/400/400",stock:15,categoria:"Manicure",activo:true,createdAt:new Date()},
  {id:"bmel2-p2",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Nail Art Kit",precio:48000,descripcion:"Kit nail art 20 piezas.",imagen:"https://picsum.photos/seed/belp12/400/400",stock:20,categoria:"Manicure",activo:true,createdAt:new Date()},
  {id:"bmel2-p3",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Extension Pestanas",precio:75000,descripcion:"Extension pestanas pelo a pelo.",imagen:"https://picsum.photos/seed/belp13/400/400",stock:10,categoria:"Pestanas",activo:true,createdAt:new Date()},
  {id:"bmel2-p4",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Depilacion Cera",precio:40000,descripcion:"Depilacion con cera tibia.",imagen:"https://picsum.photos/seed/belp14/400/400",stock:12,categoria:"Depilacion",activo:true,createdAt:new Date()},
  {id:"bmel2-p5",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Glitter Unas x10",precio:18000,descripcion:"Set glitter decoracion unas.",imagen:"https://picsum.photos/seed/belp15/400/400",stock:35,categoria:"Manicure",activo:true,createdAt:new Date()},
  {id:"bmel2-p6",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Lampara UV Unas",precio:95000,descripcion:"Lampara UV secado gel 36W.",imagen:"https://picsum.photos/seed/belp24/400/400",stock:6,categoria:"Equipos",activo:true,createdAt:new Date()},
  {id:"bmel2-p7",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Removedor Esmalte 250ml",precio:15000,descripcion:"Removedor esmalte sin acetona.",imagen:"https://picsum.photos/seed/belp25/400/400",stock:40,categoria:"Manicure",activo:true,createdAt:new Date()},
  {id:"bmel2-p8",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Serum Pestanas 5ml",precio:32000,descripcion:"Serum crecimiento pestanas.",imagen:"https://picsum.photos/seed/belp26/400/400",stock:22,categoria:"Pestanas",activo:true,createdAt:new Date()},
  {id:"bmel2-p9",storeId:"bel-mel-2",storeName:"Nails & Beauty Melgar",nombre:"Cera Depilatoria 500g",precio:28000,descripcion:"Cera depilatoria roll-on.",imagen:"https://picsum.photos/seed/belp27/400/400",stock:18,categoria:"Depilacion",activo:true,createdAt:new Date()},

  {id:"smel1-p1",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Acetaminofen 500mg x20",precio:7500,descripcion:"Analgesico antipiretico.",imagen:"https://picsum.photos/seed/salp1/400/400",stock:100,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"smel1-p2",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Suero Oral x5",precio:6500,descripcion:"Sales rehidratacion oral.",imagen:"https://picsum.photos/seed/salp2/400/400",stock:80,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"smel1-p3",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Protector Solar SPF50",precio:38000,descripcion:"Protector solar facial corporal.",imagen:"https://picsum.photos/seed/salp3/400/400",stock:30,categoria:"Cuidado Personal",activo:true,createdAt:new Date()},
  {id:"smel1-p4",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Vitamina D3 x60",precio:22000,descripcion:"Vitamina D3 2000UI capsulas.",imagen:"https://picsum.photos/seed/salp4/400/400",stock:45,categoria:"Vitaminas",activo:true,createdAt:new Date()},
  {id:"smel1-p5",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Alcohol Gel 500ml",precio:12000,descripcion:"Gel antibacterial 70% alcohol.",imagen:"https://picsum.photos/seed/salp5/400/400",stock:60,categoria:"Higiene",activo:true,createdAt:new Date()},
  {id:"smel1-p6",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Tapabocas N95 x10",precio:35000,descripcion:"Tapabocas N95 certificados.",imagen:"https://picsum.photos/seed/salp16/400/400",stock:50,categoria:"Proteccion",activo:true,createdAt:new Date()},
  {id:"smel1-p7",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Repelente Mosquitos 120ml",precio:18000,descripcion:"Repelente mosquitos familiar.",imagen:"https://picsum.photos/seed/salp17/400/400",stock:40,categoria:"Cuidado Personal",activo:true,createdAt:new Date()},
  {id:"smel1-p8",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Curitas Surtidas x50",precio:8500,descripcion:"Curitas adhesivas surtidas.",imagen:"https://picsum.photos/seed/salp18/400/400",stock:70,categoria:"Primeros Auxilios",activo:true,createdAt:new Date()},
  {id:"smel1-p9",storeId:"sal-mel-1",storeName:"Drogueria Melgar Salud",nombre:"Vitamina C 1000mg x30",precio:25000,descripcion:"Vitamina C efervescente.",imagen:"https://picsum.photos/seed/salp19/400/400",stock:55,categoria:"Vitaminas",activo:true,createdAt:new Date()},
  {id:"sesp1-p1",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Ibuprofeno 400mg x10",precio:5500,descripcion:"Antiinflamatorio analgesico.",imagen:"https://picsum.photos/seed/salp6/400/400",stock:90,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"sesp1-p2",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Omeprazol 20mg x14",precio:8500,descripcion:"Protector gastrico.",imagen:"https://picsum.photos/seed/salp7/400/400",stock:70,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"sesp1-p3",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Crema Cicatrizante 50g",precio:18000,descripcion:"Crema cicatrizante con vitamina E.",imagen:"https://picsum.photos/seed/salp8/400/400",stock:35,categoria:"Cuidado Personal",activo:true,createdAt:new Date()},
  {id:"sesp1-p4",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Termometro Digital",precio:25000,descripcion:"Termometro digital precision.",imagen:"https://picsum.photos/seed/salp9/400/400",stock:20,categoria:"Equipos",activo:true,createdAt:new Date()},
  {id:"sesp1-p5",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Multivitaminico x30",precio:28000,descripcion:"Multivitaminico completo adultos.",imagen:"https://picsum.photos/seed/salp10/400/400",stock:40,categoria:"Vitaminas",activo:true,createdAt:new Date()},
  {id:"sesp1-p6",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Jarabe Tos 120ml",precio:15000,descripcion:"Jarabe expectorante natural.",imagen:"https://picsum.photos/seed/salp20/400/400",stock:35,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"sesp1-p7",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Gasas Esteriles x10",precio:6500,descripcion:"Gasas esteriles 10x10cm.",imagen:"https://picsum.photos/seed/salp21/400/400",stock:60,categoria:"Primeros Auxilios",activo:true,createdAt:new Date()},
  {id:"sesp1-p8",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Suplemento Calcio x60",precio:32000,descripcion:"Calcio con vitamina D3.",imagen:"https://picsum.photos/seed/salp22/400/400",stock:30,categoria:"Vitaminas",activo:true,createdAt:new Date()},
  {id:"sesp1-p9",storeId:"sal-esp-1",storeName:"Farmacia San Rafael Espinal",nombre:"Crema Antiinflamatoria 60g",precio:22000,descripcion:"Crema antiinflamatoria muscular.",imagen:"https://picsum.photos/seed/salp23/400/400",stock:45,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"smel2-p1",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Gafas Formuladas",precio:180000,descripcion:"Gafas con lentes formulados.",imagen:"https://picsum.photos/seed/salp11/400/400",stock:10,categoria:"Optica",activo:true,createdAt:new Date()},
  {id:"smel2-p2",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Gafas de Sol UV400",precio:65000,descripcion:"Gafas sol proteccion UV400.",imagen:"https://picsum.photos/seed/salp12/400/400",stock:20,categoria:"Optica",activo:true,createdAt:new Date()},
  {id:"smel2-p3",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Lentes de Contacto x6",precio:85000,descripcion:"Lentes contacto mensuales.",imagen:"https://picsum.photos/seed/salp13/400/400",stock:15,categoria:"Optica",activo:true,createdAt:new Date()},
  {id:"smel2-p4",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Liquido Lentes 120ml",precio:22000,descripcion:"Liquido limpiador lentes contacto.",imagen:"https://picsum.photos/seed/salp14/400/400",stock:30,categoria:"Optica",activo:true,createdAt:new Date()},
  {id:"smel2-p5",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Estuche Gafas Premium",precio:18000,descripcion:"Estuche rigido para gafas.",imagen:"https://picsum.photos/seed/salp15/400/400",stock:25,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"smel2-p6",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Gafas Lectura +2.0",precio:45000,descripcion:"Gafas lectura pregraduadas.",imagen:"https://picsum.photos/seed/salp24/400/400",stock:18,categoria:"Optica",activo:true,createdAt:new Date()},
  {id:"smel2-p7",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Spray Limpiador Lentes",precio:12000,descripcion:"Spray limpiador lentes 50ml.",imagen:"https://picsum.photos/seed/salp25/400/400",stock:40,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"smel2-p8",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Cordon Gafas Deportivo",precio:8000,descripcion:"Cordon ajustable para gafas.",imagen:"https://picsum.photos/seed/salp26/400/400",stock:35,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"smel2-p9",storeId:"sal-mel-2",storeName:"Optica Vision Melgar",nombre:"Gafas Proteccion Luz Azul",precio:95000,descripcion:"Gafas filtro luz azul computador.",imagen:"https://picsum.photos/seed/salp27/400/400",stock:12,categoria:"Optica",activo:true,createdAt:new Date()},

  {id:"dmel1-p1",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Chaleco Salvavidas",precio:85000,descripcion:"Chaleco salvavidas homologado.",imagen:"https://picsum.photos/seed/depp1/400/400",stock:15,categoria:"Acuaticos",activo:true,createdAt:new Date()},
  {id:"dmel1-p2",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Gafas Natacion",precio:35000,descripcion:"Gafas natacion antiempanante.",imagen:"https://picsum.photos/seed/depp2/400/400",stock:25,categoria:"Natacion",activo:true,createdAt:new Date()},
  {id:"dmel1-p3",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Casco Ciclismo",precio:120000,descripcion:"Casco ciclismo certificado.",imagen:"https://picsum.photos/seed/depp3/400/400",stock:10,categoria:"Ciclismo",activo:true,createdAt:new Date()},
  {id:"dmel1-p4",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Flotador Inflable",precio:45000,descripcion:"Flotador inflable adultos.",imagen:"https://picsum.photos/seed/depp4/400/400",stock:20,categoria:"Acuaticos",activo:true,createdAt:new Date()},
  {id:"dmel1-p5",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Guantes Kayak",precio:38000,descripcion:"Guantes neopreno kayak.",imagen:"https://picsum.photos/seed/depp5/400/400",stock:12,categoria:"Acuaticos",activo:true,createdAt:new Date()},
  {id:"dmel1-p6",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Tabla Paddle Surf",precio:850000,descripcion:"Tabla paddle surf inflable completa.",imagen:"https://picsum.photos/seed/depp16/400/400",stock:3,categoria:"Acuaticos",activo:true,createdAt:new Date()},
  {id:"dmel1-p7",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Snorkel Set Completo",precio:95000,descripcion:"Set snorkel mascara y tubo.",imagen:"https://picsum.photos/seed/depp17/400/400",stock:15,categoria:"Natacion",activo:true,createdAt:new Date()},
  {id:"dmel1-p8",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Bolso Impermeable 20L",precio:65000,descripcion:"Bolso impermeable deportes acuaticos.",imagen:"https://picsum.photos/seed/depp18/400/400",stock:18,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"dmel1-p9",storeId:"dep-mel-1",storeName:"Deportes Extremos Melgar",nombre:"Aletas Natacion",precio:55000,descripcion:"Aletas natacion ajustables.",imagen:"https://picsum.photos/seed/depp19/400/400",stock:14,categoria:"Natacion",activo:true,createdAt:new Date()},
  {id:"desp1-p1",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Balon Futbol N5",precio:65000,descripcion:"Balon futbol profesional N5.",imagen:"https://picsum.photos/seed/depp6/400/400",stock:20,categoria:"Futbol",activo:true,createdAt:new Date()},
  {id:"desp1-p2",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Camiseta Deportiva",precio:42000,descripcion:"Camiseta deportiva secado rapido.",imagen:"https://picsum.photos/seed/depp7/400/400",stock:30,categoria:"Ropa Deportiva",activo:true,createdAt:new Date()},
  {id:"desp1-p3",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Tenis Futbol",precio:145000,descripcion:"Tenis futbol sala suela plana.",imagen:"https://picsum.photos/seed/depp8/400/400",stock:15,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"desp1-p4",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Mancuernas 5kg x2",precio:85000,descripcion:"Par mancuernas 5kg.",imagen:"https://picsum.photos/seed/depp9/400/400",stock:10,categoria:"Gimnasio",activo:true,createdAt:new Date()},
  {id:"desp1-p5",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Cuerda Saltar",precio:18000,descripcion:"Cuerda saltar ajustable.",imagen:"https://picsum.photos/seed/depp10/400/400",stock:35,categoria:"Gimnasio",activo:true,createdAt:new Date()},
  {id:"desp1-p6",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Guantes Portero Futbol",precio:75000,descripcion:"Guantes portero profesionales.",imagen:"https://picsum.photos/seed/depp20/400/400",stock:10,categoria:"Futbol",activo:true,createdAt:new Date()},
  {id:"desp1-p7",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Banda Elastica Ejercicio",precio:22000,descripcion:"Banda elastica resistencia media.",imagen:"https://picsum.photos/seed/depp21/400/400",stock:40,categoria:"Gimnasio",activo:true,createdAt:new Date()},
  {id:"desp1-p8",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Botella Deportiva 1L",precio:25000,descripcion:"Botella deportiva libre BPA.",imagen:"https://picsum.photos/seed/depp22/400/400",stock:45,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"desp1-p9",storeId:"dep-esp-1",storeName:"SportZone Espinal",nombre:"Rodilleras Deportivas",precio:35000,descripcion:"Rodilleras proteccion deportiva.",imagen:"https://picsum.photos/seed/depp23/400/400",stock:20,categoria:"Proteccion",activo:true,createdAt:new Date()},
  {id:"dmel2-p1",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Bicicleta MTB Rin 26",precio:650000,descripcion:"Bicicleta montana 21 velocidades.",imagen:"https://picsum.photos/seed/depp11/400/400",stock:5,categoria:"Bicicletas",activo:true,createdAt:new Date()},
  {id:"dmel2-p2",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Casco Bicicleta",precio:75000,descripcion:"Casco bicicleta ventilado.",imagen:"https://picsum.photos/seed/depp12/400/400",stock:12,categoria:"Ciclismo",activo:true,createdAt:new Date()},
  {id:"dmel2-p3",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Guantes Ciclismo",precio:32000,descripcion:"Guantes ciclismo acolchados.",imagen:"https://picsum.photos/seed/depp13/400/400",stock:20,categoria:"Ciclismo",activo:true,createdAt:new Date()},
  {id:"dmel2-p4",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Luces LED Bicicleta",precio:28000,descripcion:"Set luces LED delantera trasera.",imagen:"https://picsum.photos/seed/depp14/400/400",stock:25,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"dmel2-p5",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Candado Bicicleta",precio:35000,descripcion:"Candado combinacion acero.",imagen:"https://picsum.photos/seed/depp15/400/400",stock:18,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"dmel2-p6",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Bomba Aire Portatil",precio:28000,descripcion:"Bomba aire portatil bicicleta.",imagen:"https://picsum.photos/seed/depp24/400/400",stock:22,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"dmel2-p7",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Kit Reparacion Llantas",precio:18000,descripcion:"Kit reparacion pinchazos completo.",imagen:"https://picsum.photos/seed/depp25/400/400",stock:30,categoria:"Repuestos",activo:true,createdAt:new Date()},
  {id:"dmel2-p8",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Espejo Retrovisor Bici",precio:15000,descripcion:"Espejo retrovisor ajustable.",imagen:"https://picsum.photos/seed/depp26/400/400",stock:25,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"dmel2-p9",storeId:"dep-mel-2",storeName:"Bicicletas y Mas Melgar",nombre:"Sillin Gel Confort",precio:45000,descripcion:"Sillin gel ergonomico confort.",imagen:"https://picsum.photos/seed/depp27/400/400",stock:16,categoria:"Repuestos",activo:true,createdAt:new Date()},
  {id:"hmel1-p1",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Cojin Decorativo",precio:28000,descripcion:"Cojin decorativo 45x45cm.",imagen:"https://picsum.photos/seed/hogp1/400/400",stock:20,categoria:"Decoracion",activo:true,createdAt:new Date()},
  {id:"hmel1-p2",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Lampara Mesa LED",precio:65000,descripcion:"Lampara mesa LED regulable.",imagen:"https://picsum.photos/seed/hogp2/400/400",stock:12,categoria:"Iluminacion",activo:true,createdAt:new Date()},
  {id:"hmel1-p3",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Cuadro Decorativo",precio:45000,descripcion:"Cuadro decorativo moderno.",imagen:"https://picsum.photos/seed/hogp3/400/400",stock:15,categoria:"Decoracion",activo:true,createdAt:new Date()},
  {id:"hmel1-p4",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Organizador Cocina",precio:38000,descripcion:"Organizador cocina 3 niveles.",imagen:"https://picsum.photos/seed/hogp4/400/400",stock:18,categoria:"Cocina",activo:true,createdAt:new Date()},
  {id:"hmel1-p5",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Tapete Sala",precio:85000,descripcion:"Tapete sala antideslizante.",imagen:"https://picsum.photos/seed/hogp5/400/400",stock:8,categoria:"Decoracion",activo:true,createdAt:new Date()},
  {id:"hmel1-p6",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Cortina Blackout 2x2m",precio:95000,descripcion:"Cortina blackout termica.",imagen:"https://picsum.photos/seed/hogp16/400/400",stock:10,categoria:"Decoracion",activo:true,createdAt:new Date()},
  {id:"hmel1-p7",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Espejo Decorativo 60cm",precio:75000,descripcion:"Espejo decorativo marco dorado.",imagen:"https://picsum.photos/seed/hogp17/400/400",stock:6,categoria:"Decoracion",activo:true,createdAt:new Date()},
  {id:"hmel1-p8",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Set Toallas 3 Piezas",precio:55000,descripcion:"Set toallas algodon 3 piezas.",imagen:"https://picsum.photos/seed/hogp18/400/400",stock:15,categoria:"Bano",activo:true,createdAt:new Date()},
  {id:"hmel1-p9",storeId:"hog-mel-1",storeName:"Hogar & Deco Melgar",nombre:"Reloj Pared Moderno",precio:48000,descripcion:"Reloj pared silencioso moderno.",imagen:"https://picsum.photos/seed/hogp19/400/400",stock:12,categoria:"Decoracion",activo:true,createdAt:new Date()},
  {id:"hesp1-p1",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Pintura Interior 1 Galon",precio:42000,descripcion:"Pintura vinilo blanca interior.",imagen:"https://picsum.photos/seed/hogp6/400/400",stock:25,categoria:"Pinturas",activo:true,createdAt:new Date()},
  {id:"hesp1-p2",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Llave Paso 1/2",precio:18000,descripcion:"Llave paso PVC 1/2 pulgada.",imagen:"https://picsum.photos/seed/hogp7/400/400",stock:30,categoria:"Plomeria",activo:true,createdAt:new Date()},
  {id:"hesp1-p3",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Bombillo LED 9W",precio:8500,descripcion:"Bombillo LED 9W luz blanca.",imagen:"https://picsum.photos/seed/hogp8/400/400",stock:50,categoria:"Electrico",activo:true,createdAt:new Date()},
  {id:"hesp1-p4",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Cinta Teflon x5",precio:12000,descripcion:"Pack 5 cintas teflon plomeria.",imagen:"https://picsum.photos/seed/hogp9/400/400",stock:40,categoria:"Plomeria",activo:true,createdAt:new Date()},
  {id:"hesp1-p5",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Lija Madera x5",precio:9000,descripcion:"Pack 5 lijas madera grano 120.",imagen:"https://picsum.photos/seed/hogp10/400/400",stock:35,categoria:"Herramientas",activo:true,createdAt:new Date()},
  {id:"hesp1-p6",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Martillo Carpintero",precio:32000,descripcion:"Martillo carpintero mango fibra.",imagen:"https://picsum.photos/seed/hogp20/400/400",stock:20,categoria:"Herramientas",activo:true,createdAt:new Date()},
  {id:"hesp1-p7",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Destornillador Set x6",precio:28000,descripcion:"Set 6 destornilladores precision.",imagen:"https://picsum.photos/seed/hogp21/400/400",stock:25,categoria:"Herramientas",activo:true,createdAt:new Date()},
  {id:"hesp1-p8",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Silicona Transparente",precio:12000,descripcion:"Silicona transparente 280ml.",imagen:"https://picsum.photos/seed/hogp22/400/400",stock:40,categoria:"Adhesivos",activo:true,createdAt:new Date()},
  {id:"hesp1-p9",storeId:"hog-esp-1",storeName:"Ferrehogar Espinal",nombre:"Brocha Pintura 3 pulgadas",precio:15000,descripcion:"Brocha pintura cerda natural.",imagen:"https://picsum.photos/seed/hogp23/400/400",stock:30,categoria:"Pinturas",activo:true,createdAt:new Date()},
  {id:"hmel2-p1",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Colchon Doble Ortopedico",precio:580000,descripcion:"Colchon doble ortopedico 140x190.",imagen:"https://picsum.photos/seed/hogp11/400/400",stock:4,categoria:"Colchones",activo:true,createdAt:new Date()},
  {id:"hmel2-p2",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Almohada Fibra x2",precio:65000,descripcion:"Par almohadas fibra hipoalergenica.",imagen:"https://picsum.photos/seed/hogp12/400/400",stock:15,categoria:"Colchones",activo:true,createdAt:new Date()},
  {id:"hmel2-p3",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Sofa 3 Puestos",precio:850000,descripcion:"Sofa 3 puestos tela antimanchas.",imagen:"https://picsum.photos/seed/hogp13/400/400",stock:3,categoria:"Muebles",activo:true,createdAt:new Date()},
  {id:"hmel2-p4",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Mesa de Noche",precio:185000,descripcion:"Mesa de noche madera 2 cajones.",imagen:"https://picsum.photos/seed/hogp14/400/400",stock:6,categoria:"Muebles",activo:true,createdAt:new Date()},
  {id:"hmel2-p5",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Protector Colchon",precio:45000,descripcion:"Protector colchon impermeable.",imagen:"https://picsum.photos/seed/hogp15/400/400",stock:20,categoria:"Colchones",activo:true,createdAt:new Date()},
  {id:"hmel2-p6",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Juego Sabanas Doble",precio:85000,descripcion:"Juego sabanas microfibra doble.",imagen:"https://picsum.photos/seed/hogp24/400/400",stock:18,categoria:"Colchones",activo:true,createdAt:new Date()},
  {id:"hmel2-p7",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Comedor 4 Puestos",precio:650000,descripcion:"Comedor madera 4 puestos.",imagen:"https://picsum.photos/seed/hogp25/400/400",stock:2,categoria:"Muebles",activo:true,createdAt:new Date()},
  {id:"hmel2-p8",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Biblioteca 5 Niveles",precio:280000,descripcion:"Biblioteca madera 5 niveles.",imagen:"https://picsum.photos/seed/hogp26/400/400",stock:5,categoria:"Muebles",activo:true,createdAt:new Date()},
  {id:"hmel2-p9",storeId:"hog-mel-2",storeName:"Colchones y Muebles Melgar",nombre:"Edredon Doble Reversible",precio:120000,descripcion:"Edredon doble reversible suave.",imagen:"https://picsum.photos/seed/hogp27/400/400",stock:12,categoria:"Colchones",activo:true,createdAt:new Date()},

  {
    id: "digistore-1",
    ownerId: "owner-digi-1",
    nombre: "DigiStore",
    categoria: "Tecnologia",
    direccion: "Cra 12 #5-40, Centro Comercial Espinal Plaza",
    ciudad: "Espinal",
    telefono: "3112233445",
    descripcion: "Tienda especializada en gadgets, accesorios tecnologicos y electronica de consumo. Celulares, tablets, smartwatches y mas al mejor precio.",
    logo: "https://picsum.photos/seed/digilogo/300/300",
    banner: "https://picsum.photos/seed/digibanner/1400/500",
    calificacion: 4.7,
    totalReviews: 198,
    activo: true,
    createdAt: new Date(),
    tags: ["gadgets", "celulares", "tablets", "smartwatch"],
    horario: "Lun-Sab 9:00am - 7:00pm",
  },
  {
    id: "techpoint-1",
    ownerId: "owner-tech2-1",
    nombre: "TechPoint",
    categoria: "Tecnologia",
    direccion: "Cll 8 #10-22, Barrio El Progreso",
    ciudad: "Melgar",
    telefono: "3124455667",
    descripcion: "Computadores, impresoras, componentes y servicio tecnico rapido. Soporte a domicilio disponible para empresas y hogares en Melgar.",
    logo: "https://picsum.photos/seed/techpointlogo/300/300",
    banner: "https://picsum.photos/seed/techpointbanner/1400/500",
    calificacion: 4.6,
    totalReviews: 154,
    activo: true,
    createdAt: new Date(),
    tags: ["computadores", "impresoras", "servicio tecnico", "redes"],
    horario: "Lun-Sab 8:00am - 6:00pm",
  },
  {
    id: "electromelgar-1",
    ownerId: "owner-elec-1",
    nombre: "ElectroMelgar",
    categoria: "Tecnologia",
    direccion: "Av. Principal #20-15, Centro",
    ciudad: "Melgar",
    telefono: "3135566778",
    descripcion: "Electrodomesticos, equipos de sonido, televisores y linea blanca. Ventas a credito disponibles. Garantia oficial en todos los productos.",
    logo: "https://picsum.photos/seed/electromelgarlogo/300/300",
    banner: "https://picsum.photos/seed/electromelbanner/1400/500",
    calificacion: 4.8,
    totalReviews: 312,
    activo: true,
    createdAt: new Date(),
    tags: ["electrodomesticos", "televisores", "sonido", "credito"],
    horario: "Lun-Sab 8:00am - 7:00pm - Dom 10:00am - 4:00pm",
  },
];

export const DEMO_PRODUCTS = [
  {id:"mini-p1",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Arroz Diana 1kg",precio:5200,descripcion:"Arroz blanco de primera calidad.",imagen:"/images/products/arroz.jpg",stock:80,categoria:"Abarrotes",activo:true,createdAt:new Date()},
  {id:"mini-p2",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Aceite Girasol 1L",precio:14500,descripcion:"Aceite de girasol puro.",imagen:"/images/products/aceite.jpg",stock:45,categoria:"Abarrotes",activo:true,createdAt:new Date()},
  {id:"mini-p3",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Leche Entera 1L",precio:4800,descripcion:"Leche entera pasteurizada.",imagen:"/images/products/leche.jpg",stock:60,categoria:"Lacteos",activo:true,createdAt:new Date()},
  {id:"mini-p4",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Gaseosa 2L",precio:7500,descripcion:"Gaseosa fria varios sabores.",imagen:"/images/products/gaseosa.jpg",stock:50,categoria:"Bebidas",activo:true,createdAt:new Date()},
  {id:"mini-p5",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Jabon de Bano x3",precio:9800,descripcion:"Pack 3 jabones con glicerina.",imagen:"/images/products/jabon.jpg",stock:35,categoria:"Aseo",activo:true,createdAt:new Date()},
  {id:"mini-p6",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Azucar 1kg",precio:4200,descripcion:"Azucar blanca refinada.",imagen:"/images/products/azucar.jpg",stock:70,categoria:"Abarrotes",activo:true,createdAt:new Date()},
  {id:"mini-p7",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Cafe Sello Rojo 250g",precio:12500,descripcion:"Cafe molido colombiano.",imagen:"/images/products/cafe.jpg",stock:40,categoria:"Bebidas",activo:true,createdAt:new Date()},
  {id:"mini-p8",storeId:"minimercado-1",storeName:"Minimercado La Esquina",nombre:"Pasta Doria 500g",precio:3800,descripcion:"Pasta de trigo espagueti.",imagen:"/images/products/pasta.jpg",stock:55,categoria:"Abarrotes",activo:true,createdAt:new Date()},
  {id:"pan-p1",storeId:"panaderia-1",storeName:"Panaderia La Espiga Dorada",nombre:"Pan Artesanal x6",precio:4500,descripcion:"Pan de masa madre horneado.",imagen:"/images/products/pan.jpg",stock:30,categoria:"Panaderia",activo:true,createdAt:new Date()},
  {id:"pan-p2",storeId:"panaderia-1",storeName:"Panaderia La Espiga Dorada",nombre:"Croissant x4",precio:8000,descripcion:"Croissants de mantequilla.",imagen:"/images/products/croa.jpg",stock:20,categoria:"Panaderia",activo:true,createdAt:new Date()},
  {id:"pan-p3",storeId:"panaderia-1",storeName:"Panaderia La Espiga Dorada",nombre:"Torta de Cumpleanos",precio:65000,descripcion:"Torta personalizada.",imagen:"/images/products/torta.jpg",stock:5,categoria:"Reposteria",activo:true,createdAt:new Date()},
  {id:"pan-p4",storeId:"panaderia-1",storeName:"Panaderia La Espiga Dorada",nombre:"Almojabanas x6",precio:5500,descripcion:"Almojabanas colombianas.",imagen:"/images/products/almojabanas.jpg",stock:25,categoria:"Panaderia",activo:true,createdAt:new Date()},
  {id:"pan-p5",storeId:"panaderia-1",storeName:"Panaderia La Espiga Dorada",nombre:"Cafe Americano",precio:3500,descripcion:"Cafe de origen tolimense.",imagen:"/images/products/cafeA.jpg",stock:50,categoria:"Bebidas",activo:true,createdAt:new Date()},
  {id:"pan-p6",storeId:"panaderia-1",storeName:"Panaderia La Espiga Dorada",nombre:"Pandebono x6",precio:6000,descripcion:"Pandebono de queso.",imagen:"/images/products/pandebono.jpg",stock:20,categoria:"Panaderia",activo:true,createdAt:new Date()},
  {id:"ropa-p1",storeId:"ropa-1",storeName:"Boutique Moda Tolima",nombre:"Camiseta Basica Hombre",precio:28000,descripcion:"Camiseta algodon 100%.",imagen:"/images/products/camiseta.jpg",stock:40,categoria:"Ropa",activo:true,createdAt:new Date()},
  {id:"ropa-p2",storeId:"ropa-1",storeName:"Boutique Moda Tolima",nombre:"Jean Slim Mujer",precio:75000,descripcion:"Jean slim fit mezclilla.",imagen:"/images/products/jean.jpg",stock:25,categoria:"Ropa",activo:true,createdAt:new Date()},
  {id:"ropa-p3",storeId:"ropa-1",storeName:"Boutique Moda Tolima",nombre:"Vestido Floral",precio:65000,descripcion:"Vestido verano estampado.",imagen:"/images/products/vestido.jpg",stock:15,categoria:"Ropa",activo:true,createdAt:new Date()},
  {id:"ropa-p4",storeId:"ropa-1",storeName:"Boutique Moda Tolima",nombre:"Tenis Deportivos",precio:120000,descripcion:"Tenis unisex antideslizante.",imagen:"/images/products/tenis.jpg",stock:20,categoria:"Calzado",activo:true,createdAt:new Date()},
  {id:"ropa-p5",storeId:"ropa-1",storeName:"Boutique Moda Tolima",nombre:"Chaqueta Impermeable",precio:95000,descripcion:"Chaqueta impermeable capucha.",imagen:"/images/products/chaqueta.jpg",stock:12,categoria:"Ropa",activo:true,createdAt:new Date()},
  {id:"ropa-p6",storeId:"ropa-1",storeName:"Boutique Moda Tolima",nombre:"Bolso de Cuero",precio:85000,descripcion:"Bolso cuero sintetico.",imagen:"/images/products/bolso.jpg",stock:10,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"ferr-p1",storeId:"ferreteria-1",storeName:"Ferreteria El Constructor",nombre:"Taladro Percutor 500W",precio:185000,descripcion:"Taladro percutor con brocas.",imagen:"/images/products/taladro.jpg",stock:8,categoria:"Herramientas",activo:true,createdAt:new Date()},
  {id:"ferr-p2",storeId:"ferreteria-1",storeName:"Ferreteria El Constructor",nombre:"Pintura Blanca 1 Galon",precio:42000,descripcion:"Pintura vinilo blanca.",imagen:"/images/products/pintura.jpg",stock:20,categoria:"Pinturas",activo:true,createdAt:new Date()},
  {id:"ferr-p3",storeId:"ferreteria-1",storeName:"Ferreteria El Constructor",nombre:"Juego Destornilladores x8",precio:28000,descripcion:"Set destornilladores.",imagen:"/images/products/destornilladores.jpg",stock:15,categoria:"Herramientas",activo:true,createdAt:new Date()},
  {id:"ferr-p4",storeId:"ferreteria-1",storeName:"Ferreteria El Constructor",nombre:"Martillo Carpintero",precio:22000,descripcion:"Martillo mango madera.",imagen:"/images/products/martillo.jpg",stock:18,categoria:"Herramientas",activo:true,createdAt:new Date()},
  {id:"ferr-p5",storeId:"ferreteria-1",storeName:"Ferreteria El Constructor",nombre:"Cinta Metrica 5m",precio:12000,descripcion:"Cinta metrica acero.",imagen:"/images/products/metro.jpg",stock:25,categoria:"Herramientas",activo:true,createdAt:new Date()},
  {id:"farm-p1",storeId:"farmacia-1",storeName:"Farmacia Salud y Vida",nombre:"Acetaminofen 500mg x10",precio:4500,descripcion:"Analgesico y antipiretico.",imagen:"/images/products/acetaminofen.jpg",stock:100,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"farm-p2",storeId:"farmacia-1",storeName:"Farmacia Salud y Vida",nombre:"Vitamina C 1000mg x30",precio:18000,descripcion:"Vitamina C efervescente.",imagen:"/images/products/vitamina.jpg",stock:60,categoria:"Vitaminas",activo:true,createdAt:new Date()},
  {id:"farm-p3",storeId:"farmacia-1",storeName:"Farmacia Salud y Vida",nombre:"Crema Hidratante 200ml",precio:22000,descripcion:"Crema hidratante con aloe.",imagen:"/images/products/crema.jpg",stock:35,categoria:"Cuidado Personal",activo:true,createdAt:new Date()},
  {id:"farm-p4",storeId:"farmacia-1",storeName:"Farmacia Salud y Vida",nombre:"Alcohol Antiseptico 500ml",precio:9800,descripcion:"Alcohol antiseptico 70%.",imagen:"/images/products/alcohol.jpg",stock:50,categoria:"Primeros Auxilios",activo:true,createdAt:new Date()},
  {id:"farm-p5",storeId:"farmacia-1",storeName:"Farmacia Salud y Vida",nombre:"Ibuprofeno 400mg x10",precio:5200,descripcion:"Antiinflamatorio analgesico.",imagen:"/images/products/ibu.jpg",stock:80,categoria:"Medicamentos",activo:true,createdAt:new Date()},
  {id:"papel-p1",storeId:"papeleria-1",storeName:"Papeleria El Estudiante",nombre:"Cuaderno Norma 100 hojas",precio:8500,descripcion:"Cuaderno cuadriculado.",imagen:"/images/products/cuaderno.jpg",stock:60,categoria:"Utiles",activo:true,createdAt:new Date()},
  {id:"papel-p2",storeId:"papeleria-1",storeName:"Papeleria El Estudiante",nombre:"Lapiceros BIC x12",precio:9000,descripcion:"Caja 12 lapiceros BIC.",imagen:"/images/products/lapiceros.jpg",stock:45,categoria:"Utiles",activo:true,createdAt:new Date()},
  {id:"papel-p3",storeId:"papeleria-1",storeName:"Papeleria El Estudiante",nombre:"Resma Papel Carta",precio:22000,descripcion:"Resma 500 hojas bond.",imagen:"/images/products/papel.jpg",stock:30,categoria:"Papeleria",activo:true,createdAt:new Date()},
  {id:"papel-p4",storeId:"papeleria-1",storeName:"Papeleria El Estudiante",nombre:"Colores Faber x24",precio:18500,descripcion:"Caja 24 colores Faber.",imagen:"/images/products/colores.jpg",stock:25,categoria:"Arte",activo:true,createdAt:new Date()},
  {id:"papel-p5",storeId:"papeleria-1",storeName:"Papeleria El Estudiante",nombre:"Mochila Escolar",precio:65000,descripcion:"Mochila escolar resistente.",imagen:"/images/products/mochila.jpg",stock:12,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"tech-p1",storeId:"tecnologia-1",storeName:"TecnoShop Ibague",nombre:"Audifonos Bluetooth",precio:85000,descripcion:"Audifonos inalambricos.",imagen:"/images/products/audifonos.jpg",stock:20,categoria:"Tecnologia",activo:true,createdAt:new Date()},
  {id:"tech-p2",storeId:"tecnologia-1",storeName:"TecnoShop Ibague",nombre:"Cargador USB-C 65W",precio:45000,descripcion:"Cargador rapido USB-C.",imagen:"/images/products/cargador.jpg",stock:35,categoria:"Tecnologia",activo:true,createdAt:new Date()},
  {id:"tech-p3",storeId:"tecnologia-1",storeName:"TecnoShop Ibague",nombre:"Mouse Inalambrico",precio:55000,descripcion:"Mouse inalambrico ergonomico.",imagen:"/images/products/mouse.jpg",stock:15,categoria:"Tecnologia",activo:true,createdAt:new Date()},
  {id:"tech-p4",storeId:"tecnologia-1",storeName:"TecnoShop Ibague",nombre:"Memoria USB 64GB",precio:32000,descripcion:"Memoria USB 3.0 64GB.",imagen:"/images/products/memoria.jpg",stock:40,categoria:"Tecnologia",activo:true,createdAt:new Date()},
  {id:"tech-p5",storeId:"tecnologia-1",storeName:"TecnoShop Ibague",nombre:"Parlante Bluetooth 10W",precio:75000,descripcion:"Parlante portatil resistente.",imagen:"/images/products/parlante.jpg",stock:12,categoria:"Tecnologia",activo:true,createdAt:new Date()},
  {id:"bell-p1",storeId:"belleza-1",storeName:"Salon de Belleza Glamour",nombre:"Shampoo Keratina 500ml",precio:38000,descripcion:"Shampoo con keratina.",imagen:"/images/products/keratina.jpg",stock:25,categoria:"Belleza",activo:true,createdAt:new Date()},
  {id:"bell-p2",storeId:"belleza-1",storeName:"Salon de Belleza Glamour",nombre:"Mascarilla Capilar 300g",precio:45000,descripcion:"Mascarilla hidratante.",imagen:"/images/products/mascarilla.jpg",stock:20,categoria:"Belleza",activo:true,createdAt:new Date()},
  {id:"bell-p3",storeId:"belleza-1",storeName:"Salon de Belleza Glamour",nombre:"Esmalte de Unas x6",precio:28000,descripcion:"Set 6 esmaltes colores.",imagen:"/images/products/esmalte.jpg",stock:30,categoria:"Belleza",activo:true,createdAt:new Date()},
  {id:"bell-p4",storeId:"belleza-1",storeName:"Salon de Belleza Glamour",nombre:"Plancha de Cabello",precio:95000,descripcion:"Plancha ceramica ajustable.",imagen:"/images/products/plancha.jpg",stock:8,categoria:"Belleza",activo:true,createdAt:new Date()},
  {id:"bell-p5",storeId:"belleza-1",storeName:"Salon de Belleza Glamour",nombre:"Perfume Floral 50ml",precio:78000,descripcion:"Perfume floral femenino.",imagen:"/images/products/perfume.jpg",stock:12,categoria:"Belleza",activo:true,createdAt:new Date()},
  // MUNDO MASCOTAS TOLIMA
  {id:"masc1-p1",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Concentrado Perro Adulto 4kg",precio:68000,descripcion:"Alimento balanceado para perros adultos todas las razas.",imagen:"https://picsum.photos/seed/masc1p1/400/400",stock:30,categoria:"Alimento",activo:true,createdAt:new Date()},
  {id:"masc1-p2",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Concentrado Gato Adulto 2kg",precio:42000,descripcion:"Alimento premium para gatos adultos con taurina.",imagen:"https://picsum.photos/seed/masc1p2/400/400",stock:25,categoria:"Alimento",activo:true,createdAt:new Date()},
  {id:"masc1-p3",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Collar Antipulgas Perro",precio:28000,descripcion:"Collar antipulgas y garrapatas duracion 8 meses.",imagen:"https://picsum.photos/seed/masc1p3/400/400",stock:40,categoria:"Higiene",activo:true,createdAt:new Date()},
  {id:"masc1-p4",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Juguete Kong Rellenable",precio:35000,descripcion:"Juguete interactivo rellenable para perros.",imagen:"https://picsum.photos/seed/masc1p4/400/400",stock:15,categoria:"Juguetes",activo:true,createdAt:new Date()},
  {id:"masc1-p5",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Cama Mascotas Talla M",precio:55000,descripcion:"Cama suave y lavable para perros y gatos talla M.",imagen:"https://picsum.photos/seed/masc1p5/400/400",stock:12,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"masc1-p6",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Shampoo Perro Antipulgas",precio:22000,descripcion:"Shampoo medicado antipulgas con aloe vera.",imagen:"https://picsum.photos/seed/masc1p6/400/400",stock:35,categoria:"Higiene",activo:true,createdAt:new Date()},
  {id:"masc1-p7",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Correa Retractil 5m",precio:45000,descripcion:"Correa retractil resistente hasta 25kg.",imagen:"https://picsum.photos/seed/masc1p7/400/400",stock:20,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"masc1-p8",storeId:"mascotas-1",storeName:"Mundo Mascotas Tolima",nombre:"Snacks Premio Perro x50",precio:18000,descripcion:"Premios naturales para entrenamiento canino.",imagen:"https://picsum.photos/seed/masc1p8/400/400",stock:50,categoria:"Alimento",activo:true,createdAt:new Date()},
  // PETSHOP ANIMALCARE
  {id:"masc2-p1",storeId:"mascotas-2",storeName:"PetShop AnimalCare",nombre:"Pecera Acrilica 30L",precio:95000,descripcion:"Pecera acrilica con filtro y luz LED incluida.",imagen:"https://picsum.photos/seed/masc2p1/400/400",stock:8,categoria:"Acuarios",activo:true,createdAt:new Date()},
  {id:"masc2-p2",storeId:"mascotas-2",storeName:"PetShop AnimalCare",nombre:"Alimento Peces Tropicales",precio:15000,descripcion:"Alimento en escamas para peces tropicales 100g.",imagen:"https://picsum.photos/seed/masc2p2/400/400",stock:45,categoria:"Alimento",activo:true,createdAt:new Date()},
  {id:"masc2-p3",storeId:"mascotas-2",storeName:"PetShop AnimalCare",nombre:"Jaula Hamster Completa",precio:75000,descripcion:"Jaula para hamster con rueda, bebedero y comedero.",imagen:"https://picsum.photos/seed/masc2p3/400/400",stock:10,categoria:"Accesorios",activo:true,createdAt:new Date()},
  {id:"masc2-p4",storeId:"mascotas-2",storeName:"PetShop AnimalCare",nombre:"Arena Gato Aglomerante 4kg",precio:32000,descripcion:"Arena sanitaria aglomerante sin polvo para gatos.",imagen:"https://picsum.photos/seed/masc2p4/400/400",stock:30,categoria:"Higiene",activo:true,createdAt:new Date()},
  {id:"masc2-p5",storeId:"mascotas-2",storeName:"PetShop AnimalCare",nombre:"Vitaminas Reptiles 50ml",precio:38000,descripcion:"Suplemento vitamínico para reptiles y tortugas.",imagen:"https://picsum.photos/seed/masc2p5/400/400",stock:15,categoria:"Salud",activo:true,createdAt:new Date()},
  {id:"masc2-p6",storeId:"mascotas-2",storeName:"PetShop AnimalCare",nombre:"Comedero Automatico Mascotas",precio:85000,descripcion:"Comedero automatico programable 2L capacidad.",imagen:"https://picsum.photos/seed/masc2p6/400/400",stock:7,categoria:"Accesorios",activo:true,createdAt:new Date()},
  // VETERINARIA HUELLITAS
  {id:"masc3-p1",storeId:"mascotas-3",storeName:"Veterinaria Huellitas",nombre:"Vacuna Antirrábica Perro",precio:35000,descripcion:"Vacuna antirrábica certificada para perros.",imagen:"https://picsum.photos/seed/masc3p1/400/400",stock:20,categoria:"Salud",activo:true,createdAt:new Date()},
  {id:"masc3-p2",storeId:"mascotas-3",storeName:"Veterinaria Huellitas",nombre:"Desparasitante Interno x3",precio:22000,descripcion:"Desparasitante interno para perros y gatos.",imagen:"https://picsum.photos/seed/masc3p2/400/400",stock:50,categoria:"Salud",activo:true,createdAt:new Date()},
  {id:"masc3-p3",storeId:"mascotas-3",storeName:"Veterinaria Huellitas",nombre:"Alimento Terapeutico Renal",precio:78000,descripcion:"Alimento veterinario para mascotas con problemas renales.",imagen:"https://picsum.photos/seed/masc3p3/400/400",stock:12,categoria:"Alimento",activo:true,createdAt:new Date()},
  {id:"masc3-p4",storeId:"mascotas-3",storeName:"Veterinaria Huellitas",nombre:"Kit Primeros Auxilios Mascotas",precio:45000,descripcion:"Kit completo de primeros auxilios para mascotas.",imagen:"https://picsum.photos/seed/masc3p4/400/400",stock:15,categoria:"Salud",activo:true,createdAt:new Date()},
  {id:"masc3-p5",storeId:"mascotas-3",storeName:"Veterinaria Huellitas",nombre:"Antipulgas Pipeta x3",precio:28000,descripcion:"Pipetas antipulgas y garrapatas para perros.",imagen:"https://picsum.photos/seed/masc3p5/400/400",stock:40,categoria:"Salud",activo:true,createdAt:new Date()},
  {id:"masc3-p6",storeId:"mascotas-3",storeName:"Veterinaria Huellitas",nombre:"Elizabethan Collar Talla M",precio:18000,descripcion:"Collar isabelino para recuperacion post cirugia.",imagen:"https://picsum.photos/seed/masc3p6/400/400",stock:20,categoria:"Accesorios",activo:true,createdAt:new Date()},
];
